// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * 创建边栏使您能够：
 - 创建有序的文档组
 - 为该组的每个文档呈现一个侧边栏
 - 提供下一个/上一个导航
  侧边栏可以从文件系统生成，也可以在此处显式定义。
  根据需要创建任意数量的侧边栏。

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 默认情况下，Docusaurus 会从 docs 文件夹结构生成侧边栏
  // tutorialSidebar: [
  //     {type: 'autogenerated',
  //       dirName: '.'}  // 从 docs 文件夹 (或 versioned_docs/<version>) 生成侧边栏
  // ],

  // 但您可以手动创建侧边栏
  tutorialSidebar: [
    'intro',
    'login',
    // 代理商
    {
        type: 'category',
        label: '代理商', // 侧边栏标签文字
        collapsible: true,
        // 侧边栏初始展示时是展开的状态
        // collapsed: false,
        // 绑定文档
        link: {
            type: 'doc', //
            id: 'agent/index',
        },
        items: [
            {
                type: 'category',
                label: '代理商中台', // 侧边栏标签文字
                collapsible: true,
                link: {
                    type: 'doc',
                    id: 'agent/agentBackend/agentBackend',
                },
                items:[
                    'agent/agentBackend/purchaseIn',
                    'agent/agentBackend/purchaseReturn',
                    'agent/agentBackend/consignmentIn',
                    'agent/agentBackend/consignmentReturn',
                    'agent/agentBackend/saleIn',
                    'agent/agentBackend/saleReturn',
                    'agent/agentBackend/stockOut',
                ]
            },
            {
                type: 'category',
                label: '代理商门店', // 侧边栏标签文字
                link: {
                    type: 'doc',
                    id: 'agent/agentStore/agentStore',
                },
                items:[
                    'agent/agentStore/dayEnd',
                ]
            },
        ],
    }, // 直属经销商
    {
        type: 'category',
        label: '直属经销商', // 侧边栏标签文字
        "description" : "直属经销商",
        // 绑定文档
        link: {
            type: 'doc', // 值:doc 文档
            id: 'directDealer/index',
        },
        collapsible: true,
        // 侧边栏初始展示时是展开的状态
        // collapsed: false,
        items: [
            {
                type: 'category',
                label: '直属经销商中台', // 侧边栏标签文字
                collapsible: true,
                link: {
                    type: 'doc',
                    id: 'directDealer/directDealerBackend/directDealerBackend',
                },
                items:[
                    'directDealer/directDealerBackend/purchaseIn',
                    'directDealer/directDealerBackend/purchaseReturn',
                    'directDealer/directDealerBackend/consignmentIn',
                    'directDealer/directDealerBackend/consignmentReturn',
                ]
            },
            {
                type: 'category',
                label: 'directDealerStore', // 侧边栏标签文字
                "description" : "代理商门店",
                link: {
                    type: 'doc',
                    id: 'directDealer/directDealerStore/directDealerStore',
                },
                items:[

                ]
            },
        ],
    },
    //   员工管理
    {
        type: 'category',
        label: '员工管理', // 侧边栏标签文字
        "description" : "员工管理",
        // 绑定文档
        link: {
            type: 'doc', // 值:doc 文档
            id: 'staffManagement/staffManagement',
            // "description": "5 minutes to learn the most important Docusaurus concepts."
        },
        collapsible: true,
        // 侧边栏初始展示时是展开的状态
        // collapsed: false,
        items: [
            'staffManagement/add',
            'staffManagement/update'
        ],
    },

    // 供应链管理
    // {
    //   type: 'category',
    //   label: '供应链管理', // 侧边栏标签文字
    //   "description" : "供应链管理",
    //   // 创建卡片
    //   link: {
    //     title: '供应链管理',
    //     type: 'generated-index', // 值:doc 文档
    //     image: '/img/docusaurus.png',
    //     // "description": "5 minutes to learn the most important Docusaurus concepts."
    //   },
    //   collapsible: true,
    //   // 侧边栏初始展示时是展开的状态
    //   // collapsed: false,
    //   items: [
    //       'chainManagement/ScmConsigneeIn',
    //       'chainManagement/ScmConsigneeOut'
    //   ],
    // },

  ],
};

export default sidebars;
